dist: bionic
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - '10'
  - '8'
  - '6'
cache:
  directories:
    - node_modules
stages:
  - lint
  - test
  - npm release
script:
  - 'npm run test:unit'
jobs:
  include:
    - stage: lint
      node_js: '10'
      script: 'npm run lint'
    - stage: npm release
      node_js: '10'
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
