version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  docker:
    - image: cimg/node:14.19

jobs:
  security-scans:
    <<: *defaults
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Set npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - run:
          name: Install
          command: npm install
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  test:
    <<: *defaults
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Set npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  release:
    <<: *defaults
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Set npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
      - run:
          name: Install
          command: npm install
      - run:
          name: Release
          command: npx semantic-release@17

workflows:
  version: 2
  test:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
          filters:
            branches:
              ignore:
                - master
      - security-scans:
          name: Security Scans
          context:
            - open_source-managed
            - nodejs-install
      - test:
          name: Test
          context: nodejs-install
      - release:
          name: Release
          requires:
            - Test
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
